In [17]:
import numpy as np

In [18]:
#addition
np.add(45,20)

65

In [19]:
#subtraction
np.subtract(45,23)

22

In [20]:
np_daily_wage = np.array([7,9,13,8,11])*15

In [21]:
print(np_daily_wage)

[105 135 195 120 165]


In [22]:
sum(np_daily_wage)

720

In [23]:
np_weekly_hrs = np.array([23,41,55,47,38])
#week with more than 40 hrs
np_weekly_hrs[np_weekly_hrs>40]

array([41, 55, 47])

In [24]:
np_weekly_hrs[np_weekly_hrs!=40]

array([23, 41, 55, 47, 38])

In [25]:
#logical operations
np.logical_and(np_weekly_hrs>20, np_weekly_hrs<50)

array([ True,  True, False,  True,  True])

In [26]:
np.logical_not(np_weekly_hrs>35)

array([ True, False, False, False, False])

In [27]:
#create two arrays of the same shape
array_a = np.array([2,3,5,8])
array_b = np.array([.3,.3,.3,.3])

In [28]:
#multiplying arrays
array_a *array_b

array([0.6, 0.9, 1.5, 2.4])

In [29]:
#create a variable with a scaler value
Scalar_c = .3

In [30]:
array_a * Scalar_c

array([0.6, 0.9, 1.5, 2.4])