In [32]:
import numpy as np

In [33]:
first_numpy_array = np.array([1,2,3,4])

In [34]:
print(first_numpy_array)

[1 2 3 4]


In [35]:
array_with_zeros = np.zeros((3,4))
array_with_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
array_with_empty = np.empty((2,3))
array_with_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np_arange = np.arange(12)
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [39]:
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
np_linspace = np.linspace(1,6,5)
print(np_linspace)

[1.   2.25 3.5  4.75 6.  ]


In [41]:
oneD_array = np.arange(15)
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [42]:
TwoD_array = oneD_array.reshape(3,5)
print(TwoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [43]:
ThreeD_array = np.arange(27).reshape(3,3,3)
print(ThreeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
